### ISSUE TITLE
run tests with strict.on()

### ISSUE THREAD

**Issue by olegrok** [tarantool/luatest#104]
Enable strict mode by default when we run tests. It helps to avoid some confusing situations when we get some test result on debug and release tarantools.

Debug tarantool enables strict mode by default.

**Comment by printercu** [comment]
`test/helper.lua` is loaded before any test files. You can add `require('strict').on()` to the top of it.

Does it solve the issue?

**Comment by olegrok** [comment]
It solves a problem only for me. But I propose to do it globally. This will break backward compatibility a bit, but I think it's worth it.

**Comment by rosik** [comment]
Proposal rejected. Closing.
