### ISSUE TITLE
assert_items_equals doesn't properly work with tables with string number keys

### ISSUE THREAD

**Issue by Satbek** [tarantool/luatest#117]
``t.assert_items_equals`` doesn't raise on such arguments: {["1"] = 1,["2"] = 2,["3"] = 3}, {3, 2, 1}. But it should raise, because the table are completely different

```lua
tarantool> t.assert_items_equals({1,2,3}, {3,2,1})
---
...

tarantool> t.assert_items_equals({[1] = 1,[2] = 2,[3] = 3}, {[1] = 3,[2] = 2, [3] = 1})
---
...

tarantool> t.assert_items_equals({["1"] = 1,["2"] = 2,["3"] = 3}, {3, 2, 1}) --doesn't raise an error
...
```

but ``t.assert_equals`` raises
```lua
tarantool> t.assert_items_equals({["1"] = 1,["2"] = 2,["3"] = 3}, {1,2,3})
---
...

tarantool> t.assert_equals({["1"] = 1,["2"] = 2,["3"] = 3}, {1,2,3})
---
- error:
    status: fail
    class: LuatestError
    message: 'expected: {1, 2, 3}

      actual: {["1"] = 1, ["2"] = 2, ["3"] = 3}'
...

tarantool> t.assert_equals({[1] = 1,[2] = 2,[3] = 3}, {1,2,3})
---
...

```

**Comment by Satbek** [comment]
I have read the documentation for ``assert_items_equals`` , and there are said "Checks equality of tables regardless of the order of elements." So, I think it isn't a bug, because items are equal, but in my opinion people mostly use it to compare arrays, so at this case ``assert_items_equals`` is not enough.

**Comment by rosik** [comment]
The "order" implies it should be an "array". At least it shouldn't have string keys. Guess we can fix it.

**Comment by ylobankov** [comment]
It's not a bug. It's expected behavior. The `t.assert_items_equals` function is exactly for comparison things like `{["1"] = 1, ["2"] = 2, ["3"] = 3}` and `{3, 2, 1}`. It checks the equality of tables by **field values**, field keys are not considered. 

The documentation says `Checks equality of tables regardless of the order of elements` and it really misleads people. I think we need to change this statement to `Checks equality of tables by field values` which is more comprehensible.

**Comment by Totktonada** [comment]
Both interpretations make sense, so I looked at the [origin](https://luaunit.readthedocs.io/en/latest/#assertItemsEquals):

> ```lua
> assertItemsEquals(actual, expected[, extra_msg])
> ```
>
> **Alias:** `assert_items_equals()`
>
> Assert that two tables contain the same items, irrespective of their keys. If provided, extra_msg is a string which will be printed along with the failure message.
>
> This function is practical for example if you want to compare two lists but where items are not in the same order:
>
> ```lua
> lu.assertItemsEquals( {1,2,3}, {3,2,1} ) -- assertion succeeds
> ```
>
> The comparison is not recursive on the items: if any of the items are tables, they are compared using table equality (like as in `assertEquals()`), where the key matters.
>
> ```lua
> lu.assertItemsEquals( {1,{2,3},4}, {4,{3,2,},1} ) -- assertion fails because {2,3} ~= {3,2}
> ```

So Yaroslav wins in the Yaroslav versus Yaroslav debate :)

I think we should keep existing behaviour and describe it cleanly. If we'll see a real need in assertions specific for arrays, we can add them and use the `array` word in its names to make them less ambiguous.

What I would also like to note about descriptions:

* luaunit's description resolves any possible ambiguity, as I see. It would be nice to make luatest documentation be on the same quality level.
* Assertions description in luaunit are splitted per groups and so they are much easier to read. It would be nice to group our assertions too (in the same way or another meaningful way).
