### ISSUE TITLE
Add assert_lt, gt, le, ge functions

### ISSUE THREAD

**Issue by rosik** [tarantool/luatest#125]
It's helpful sometimes. Copy-paste it from here: https://github.com/tarantool/cartridge/blob/98d616ae50304c42dd8e19dee92f4480e220c229/test/helper.lua#L135-L153

**Comment by olegrok** [comment]
Seems like duplicate of https://github.com/tarantool/luatest/issues/76

**Comment by Steap2448** [comment]
Closed via #126
