### ISSUE TITLE
Different summary with and without failed tests

### ISSUE THREAD

**Issue by ligurio** [tarantool/luatest#172]
With zero failed tests (`failures`):

`Ran 9 tests in 3.529 seconds, 9 successes, 0 failures, 3 skipped`

With non-zero failed tests (`fail`):

`Ran 11 tests in 21.986 seconds, 10 successes, 1 fail, 4 skipped`

luatest 0.5.5

Feel free to close a ticket, I just discovered it and

**Comment by rosik** [comment]
+1. `conditional_plural` is nasty. I'd fully tear it off.

**Comment by NickVolynkin** [comment]
There's more than a single line here.

For consistency, we can use past simple. It doesn't have single/plural forms.

> 10 successed, 1 failed, 4 skipped
