### ISSUE TITLE
Assert messages in logs

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/luatest#187]
Is there any way to assert log messages in tests?
Maybe we should add that assertion?

**Comment by ylobankov** [comment]
@yngvar-antonsson We have recently added [server:grep_log()](https://github.com/tarantool/luatest/blob/8b14346dcc4c6423dcbf1704fc7383a0f6c4d111/luatest/server.lua#L580) function. I believe you can use it in such a way:

```lua
g.test_assert_log_message = function()
    t.helpers.retrying({}, function()
        local msg = 'some log message'
        t.assert(g.server:grep_log(msg))
    end)
end
```

Will it work for you?

**Comment by yngvar-antonsson** [comment]
Yes, it will. Closed.
