### ISSUE TITLE
Add helpers to work with the test server box

### ISSUE THREAD

**Issue by locker** [tarantool/luatest#189]
There are lots of Tarantool tests that work with spaces. If we migrate them to luatest, we'll have to use evals, e.g.:

```lua
    t.assert_equals(
        g.server:eval("return index3:select{}"),
            {{30, 3, 9, 30, 4, 100},
            {3, 4, 5, 6, 7},
            {4, 5, 6, 7, 8},
            {11, 2, 13, 24, 15, 100}})
```

This is inconvenient. It'd be better if we could use box-like API instead, e.g:

```lua
    t.assert_equals(g.server.box.space.test_space.index.pk:select{}, ...)
```

The easiest way to achieve that is probably allow tests to use the net.box connection established by the test suite, because the latter already implements box-like API.

Can we extend the test suite API to allow using any box function, e.g.

```lua
    g.server.box.snapshot()
    local info = g.server.box.info()
```

?

**Comment by Totktonada** [comment]
There is `g.server.net_box`. It is just net.box connection, so you can use select/insert and so on. We can add info functions to [luatest_helpers.server](https://github.com/tarantool/tarantool/blob/71a789f07ceaca3c1c6fdaeeb0f34b3c86e49986/test/luatest_helpers/server.lua) on the tarantool side.

I hope we'll move those server / cluster helpers (as well as the default instance file) to luatest itself sooner or later.

**Comment by locker** [comment]
> There is `g.server.net_box`. It is just net.box connection, so you can use select/insert and so on. We can add info functions to [luatest_helpers.server](https://github.com/tarantool/tarantool/blob/71a789f07ceaca3c1c6fdaeeb0f34b3c86e49986/test/luatest_helpers/server.lua) on the tarantool side.

Awesome! I didn't know. Probably, because it isn't used in existing tests in Tarantool. For some reason, they use evals instead (e.g. see https://github.com/tarantool/tarantool/pull/6557).

> 
> I hope we'll move those server / cluster helpers (as well as the default instance file) to luatest itself sooner or later.

Can we automate it somehow? That is, if you called `g.server.box.this.that`, it would call `box.this.that` on the server?

**Comment by locker** [comment]
Also, `net.box` doesn't let you create spaces on the remote host, which is must-have for tests.

**Comment by Totktonada** [comment]
> > I hope we'll move those server / cluster helpers (as well as the default instance file) to luatest itself sooner or later.
> 
> Can we automate it somehow? That is, if you called `g.server.box.this.that`, it would call `box.this.that` on the server?

I would propose to look at [luatest_helpers.server](https://github.com/tarantool/tarantool/blob/71a789f07ceaca3c1c6fdaeeb0f34b3c86e49986/test/luatest_helpers/server.lua) and add a method (or `__index` metafield) to it. I guess the method will be a simple wrapper around `self.net_box:call()`.

> Also, `net.box` doesn't let you create spaces on the remote host, which is must-have for tests.

Should it accept a schema in the [tarantool/ddl](https://github.com/tarantool/ddl#input-data-format) way (accept a declaration of the schema)? If so, is not that quite large amount of work? Maybe [server:exec()](https://github.com/tarantool/luatest/pull/178) is enough to create spaces in a visually structured way?

**Comment by alyapunov** [comment]
Net box can't do **a lot of** things, for instance:
box.cfg{}
box.cfg
box.schema
box.func
box.info()
box.slab.stats()

**Comment by locker** [comment]
> Should it accept a schema in the [tarantool/ddl](https://github.com/tarantool/ddl#input-data-format) way (accept a declaration of the schema)? If so, is not that quite large amount of work? Maybe [server:exec()](https://github.com/tarantool/luatest/pull/178) is enough to create spaces in a visually structured way?

I was thinking about something like this: `__index` returns a new object that stores the name of the indexed member; an attempt to call the object, sends eval request to a remote instance, passing the stored string. This would work for every function defined on a remote server. Is it possible to implement?

**Comment by locker** [comment]
I recently found out that it's possible to call `require('luatest').assert()` from inside a function executed remotely with `exec`:

```lua
g.server:exec(function()
    local t = require('luatest')
    t.assert(true)
end)
```

This means that we can wrap a whole test that is supposed to run on a Tarantool instance in an `exec` without using `eval` at all, which is really nice. We don't need any special helpers to work with a remote box instance in this case.

**Comment by ylobankov** [comment]
@locker Can we close this issue?

**Comment by locker** [comment]
> @locker Can we close this issue?

Yes.
