### ISSUE TITLE
Exclude 'flatten' file from coverage by default

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/luatest#190]
tarantool/crud produce 'flatten' file while flattening. 

```lua
crud.insert_object('space', obj)
```

```bash
.rocks/bin/luatest integration_api --coverage
.rocks/bin/luacov .
Couldn't open flatten: No such file or directory
```

I propose to exclude it from coverage collection by default:

```lua
exclude = {
	'flatten',
}
```

**Comment by Totktonada** [comment]
tarantool/crud does not create any temporary files. I think you're about the following code:

```lua
flatten_func = assert(load(code, '@flatten', 't', env))
```

https://github.com/tarantool/crud/blob/5e8c91e39bd608804e0ab85989a537dfd63ec7bf/crud/common/utils.lua#L116

See https://github.com/keplerproject/luacov/issues/55#issuecomment-419087943.

It seems, we should not use `@` here. I guess that the best options is to leave it `nil` to make equal to `code`, see docs [here](https://www.lua.org/manual/5.2/manual.html#pdf-load) and [here](https://www.lua.org/manual/5.2/manual.html#4.9).

**Comment by Totktonada** [comment]
Filed https://github.com/tarantool/crud/issues/249 against crud.

**Comment by ylobankov** [comment]
Looks like not a luatest issue. So closing it. Feel free to reopen if it is related to luatest.
