### ISSUE TITLE
Two 'helpers' and 'assertions', unclear which one has what and when should be used

### ISSUE THREAD

**Issue by Gerold103** [tarantool/luatest#192]
Both luatest and `test/` folder in Tarantool provide `helpers` and `assertions`. Like this: `require('test.luatest_helpers')` and `require('luatest').helpers`. The same with the assertions.
It is unclear which one should be used when. Especially hard it is to navigate the sources, because you have 2 files both for helpers and assertions. In total 4 files just to get API similar to `test_run:wait_cond()` or `assert(...)` in the old diff-based tests. When we had all "helpers" in a single file `test_run.lua`.

Also it just looks ugly in the code when you need to take some assertions/helpers from one variable, some from another.

They better be merged somehow. At least assertions+assertions and helpers+helpers.

**Comment by NickVolynkin** [comment]
DoD: 

- [ ] merge all functionality to luatest
- [ ] change all imports to `require('luatest').helpers`; fix all tests which break after this change
- [ ] update documentation on updated helpers and assertions

There are many helpers and assertions to work with, so we should split this issue into several atomic issues.

**Comment by ylobankov** [comment]
For now, we have only one package with luatest helpers (`luatest_helpers`) with two modules inside: `cluster.lua` and `server.lua`. The `cluster.lua` and `server.lua` modules can be ported to luatest later (if we find it useful). Anyway, porting them is out of the scope of this issue, so I think we can consider this ticket closed.
