### ISSUE TITLE
How to run a test with particular configuration (group)?

### ISSUE THREAD

**Issue by Totktonada** [tarantool/luatest#198]
Usually I use `-p`, but here I don't find a way to filter test/group this way.

**Comment by ylobankov** [comment]
> Usually I use `-p`, but here I don't find a way to filter test/gruop this way.

To run all tests from a particular group you should pass the group name to luatest as an argument:
```
$ .rocks/bin/luatest <group name> -v
```

To run a particular test from a particular group you should pass `<group name>.<test name>` to luatest as an argument:
```
$ .rocks/bin/luatest <group name>.<test name> -v
```

From luatest help command:
```
.rocks/bin/luatest -h
Usage: luatest [options] [files or dirs...] [testname1 ...]
Options:
  -h, --help:             Print this help
  --version:              Print version information
  -v, --verbose:          Increase verbosity
  -q, --quiet:            Set verbosity to minimum
  ...
  test_name, ...:         Tests to run in the form of group_name or group_name.test_name
  ```

To run tests from a particular group matching to some test name pattern you should pass the group name and `-p <test name pattern>` to luatest.
```
$ .rocks/bin/luatest <group name> -p <test name pattern> -v
```

**Comment by Totktonada** [comment]
Nice!

Can we add the recipe into README on to wiki and link from README?

**Comment by ylobankov** [comment]
> Nice!
> 
> Can we add the recipe into README on to wiki and link from README?

Yes, will do.
