### ISSUE TITLE
Run tarantool in a proper directory

### ISSUE THREAD

**Issue by alyapunov** [tarantool/luatest#199]
I usually build tarantool in a subdirectory in tarantool project tree. For example:
`git clone https://github.com/tarantool/tarantool && cd ./tarantool && mkdir build && cd ./build && cmake .. && make -j && make test`.
When I run common test they create necessary files in build directory and that is correct. But when I run luatest, it creates *.snap and *.xlog files in parent folder, in tarantool. That is wrong, all path must be relative to build folder.

**Comment by ylobankov** [comment]
Looks like it is not relevant anymore. Now all logs are stored in `${VARDIR}/<server_alias-id>` directory where VARDIR is `/tmp/t` by default.
