### ISSUE TITLE
Add depth to assert_covers

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/luatest#203]
Now it doesn't work:
```lua
t.assert_covers(
    {a = {b = 'c', d = 'e'}, f = 'g'}, 
    {a = {b = 'c'}}
)
```
Because {b = 'c', d = 'e'} ~= {b = 'c'}
I propose to add depth parameter to assert_covers to assert coverage of inner tables

**Comment by Gerold103** [comment]
I faced the same issue while trying to use this assertion for vshard config tests. Please, bump the priority. This function is barely useful now except for trivial cases.

**Comment by locker** [comment]
Done unconditionally (without a parameter) in:
- https://github.com/tarantool/luatest/pull/388
