### ISSUE TITLE
assert_not_equals prints confusing message 

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/luatest#206]
```lua
t.assert_not_equals(a, b)
```
Assert message: "Received unexpected value: 0"
It would be nice to see the values of `a` and `b`.

**Comment by ylobankov** [comment]
> ```lua
> t.assert_not_equals(a, b)
> ```
> 
> Assert message: "Received unexpected value: 0" It would be nice to see the values of `a` and `b`.

Why? IMHO, there is no need to print the value for `a` and the value for `b` because `a` and `b` are equal. But the error message itself sounds confusing to me. I would change it to something like this: `Actual and expected values are equal: <value>`.
