### ISSUE TITLE
Add some kind of `workdir` option to `test.luatest_helpers.server` or `luatest.Server`

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/luatest#214]
# Current state
Currently, one can only specify a `work_dir` that will be directly passed to `box.cfg` (via `workdir` option passed to luatest.Server, via the `TARANTOOL_WORKDIR` environment variable, or via explicitly specifying `work_dir` in `box.cfg`), which implies that the test server will be run in the specified directory.

# Scenario
Consider the following scenario: one might need to start a Tarantool instance from a certain _snapshot_ or set of _xlogs_ — for instance, to test Tarantool over an older schema version:
https://github.com/tarantool/tarantool/blob/2b1dbe921d004b6118afecc493a12c65c9edc9bc/test/xlog/upgrade/how_to_add_new_test.md?plain=1#L14-L19

# Issue
Currently, using luatest, we can only run a Tarantool instance directly from a directory specified via `work_dir` (e.g., from a source directory), which is pretty dirty, and also doesn't work for read-only files systems, where Tarantool sources can be stored when running a CI job.

# Feature
What we would actually want to do, is copy the specified directory to the current test-suite's _vardir_ and launch a Tarantool instance from there.

# Example implementation
We already have this feature implemented in diff-tests (via the `with workdir=` clause, which one can pass to `inspector:cmd`:
https://github.com/tarantool/test-run/blob/d16cbdc2702e7d939d5d34e41730fd83d2c65879/lib/preprocessor.py#L274-L284

# Needed for
Last but not least, this blocks tarantool/tarantool#6571, which requires this feature.

**Comment by Totktonada** [comment]
Can you copy the snapshot to the workdir before starting the server?

**Comment by CuriousGeorgiy** [comment]
@Totktonada and duplicate this code for every subsequent _upgrade_ test?

**Comment by Totktonada** [comment]
I guess it means 'Yes'. So you can implement it in the server helper.

**Comment by NickVolynkin** [comment]
You can just update the `intitialize()` method in https://github.com/tarantool/tarantool/blob/197088c3af6439b2e2e6f94d97f5aed728a8c6a0/test/luatest_helpers/server.lua#L41.

Add a parameter for the path to directory from which to copy snapshot&xlogs into the `workdir`.

**Comment by CuriousGeorgiy** [comment]
FTWAI I am taking this issue: please transfer this issue to tarantool/tarantool repository, where it belongs (related to luatest helpers, which AFAIU, are maintained under tarantool/tarantool), and also so that I can self-assign it.

**Comment by Totktonada** [comment]
I would prefer to don't move and just close this issue from the commit message in tarantool's commit.

Issues transition break existing backlinks, sometimes break labels. I prefer to avoid it generally.
