### ISSUE TITLE
Prepare release 0.5.7

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/luatest#216]
- [ ] Write changelogs
- [ ] Define clear versioning policy (use semver?)

**Comment by artembo** [comment]
All preparation is done here https://github.com/tarantool/luatest/blob/master/.github/workflows/push_rockspec.yaml We just need to push the new tag.

@NickVolynkin What do you mean about version policy? What do we need to define? semver is used for the repository, see the changelog, please.
