### ISSUE TITLE
Repeat group of tests

### ISSUE THREAD

**Issue by yngvar-antonsson** [tarantool/luatest#217]
Now luatest opt `repeat` support only single test repeating. But sometimes we need to repeat group of tests, not the individual tests.

**Comment by ylobankov** [comment]
Will it work for you?

```
for i in {1..10}; do ./bin/luatest -v --shuffle none test/repeat_test.lua; done
```

**Comment by artembo** [comment]
Obviously, it will work, but take a look:

    for i in {1..10}; do ./bin/luatest -v --shuffle none test/repeat_test.lua; done

Looks ugly...

Probably, It should be more convenient and beautiful to do like this:

    ./bin/luatest -v --shuffle none --group-repeat 10 test/repeat_test.lua
