### ISSUE TITLE
Hard to see whether particular line of code was executed or not

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/luatest#221]
I made a mistake: wrote `g.before_test = function() ...` instead of `g.before_test(function() ...)`
There were no errors in luatest, just 2 failed test cases.
I took quite some time to understand that the before_test hooks weren't run, and to check that I had to add `assert(false)` to the hook.

Another example: we set long timeouts on most of our `wait_for` functions. ~100 seconds is typical.
When the test hangs for some reason, it's impossible to see where it hung until the huge timeout passes.
I have to insert `assert(false)` every couple of lines, to find the place that hangs.

I'd be nice to print something to `.result` file, for example: `before_each running`, `before_test (test_name) running`, `test_name running`.

Maybe even log specific actions somewhere, like it's done in test-run's `var/log/XXX_suite_name.log`:
`eval something on that server`,
`assert something is equal to something`,
`wait for this and that, expected. ..., got ..., try again in 0.1 seconds`

**Comment by ylobankov** [comment]
Finally, it should be fixed by https://github.com/tarantool/luatest/pull/347.
