### ISSUE TITLE
Q: parameter `self` in before_all/after_all callbacks

### ISSUE THREAD

**Issue by rosik** [tarantool/luatest#28]
I've read in the luaunit doc, that one can specify tests setup/teardown in the folowing way:

```lua
local g = require('luatest').group('mygroup')
function g:setup()
    -- do something with self
end
```

And for before_all/after_all callbacks there is nothing similar. I can't see the `self` param is passed.

So, my questions are:

1. Is it correct (that before_all doesn't have self param) or just my misunderstanding?
2. Is there a reason to avoid passing it?
3. Would do you think about adding this feature?

**Comment by printercu** [comment]
I've not seen this example before. Copied from https://luaunit.readthedocs.io/en/latest/ :

```lua
TestLogger = {}
    function TestLogger:setUp()
        -- define the fname to use for logging
        self.fname = 'mytmplog.log'
        -- make sure the file does not already exists
        os.remove(self.fname)
    end

    function TestLogger:testLoggerCreatesFile()
        initLog(self.fname)
        log('toto')
        -- make sure that our log file was created
        f = io.open(self.fname, 'r')
        lu.assertNotNil( f )
        f:close()
    end

    function TestLogger:tearDown()
        -- cleanup our log file after all tests
        os.remove(self.fname)
    end
```

Let's decide if we need this in luatest. In luaunit they need this to store group's local variables, as it encourages using multiple groups in single file. I se no similar usecase for luatest as it encourages use separate file for separate group.

So here are different approaches:

```lua
-- 1)
local var = 1
g.test_smth = function()
  use(var)
end

-- 2)
local var
g.setup = function() { var = 1 }
g.test_smth = function()
  use(var)
end

-- 3)
g.setup = function() { g.var = 1 }
g.test_smth = function()
  use(g.var)
end

-- luaunit way
function g:setup() { self.var = 1 }
function g:test_smth()
  use(self.var)
end
```

It's not hard to implement (just add an argument to function call), but I don't know if this going to make tests more or less readable and clear. Looks like it just add's one more way to do the stuff which is neither more obvious nor more compact. Any thoughts?

**Comment by rosik** [comment]
From the point of view of respect to original API, which I usually follow, I would use `g:setup()`. So, it would be more obvious to keep before_all after_all API the same.

**Comment by rosik** [comment]
Seems we can live without it. Closing
