### ISSUE TITLE
Test order is unexpected and misleading

### ISSUE THREAD

**Issue by olegrok** [tarantool/luatest#29]
Yes, sometimes it's useful. But expected behavior is test will be launched in user-defined order.

It’s especially important for tests in group.

**Comment by olegrok** [comment]
First idea, it's redefine __newindex metamethod for groups. That allows to add some internal logic to keep test order

**Comment by artur-barsegyan** [comment]
By the way, at now, `pytest == 4.0.0` has user-defined test order execution.
