### ISSUE TITLE
Show log of tests

### ISSUE THREAD

**Issue by alyapunov** [tarantool/luatest#308]
Now log sometimes seems not to work at all, and even it works, it must be saved when tests are completed.
```lua
pg.test_abort_readers_of_insertion = function(cg)
    t.tarantool.skip_if_not_debug()
    require('log').error('XXXXX 1') -- I don't see this message anywhere
    cg.server:exec(function(idx)
        require('log').info('XXXXX 2') -- I see this only while the test runs, the log file disappears then.
        require('fiber').sleep(10)
```
Sometimes logs are the only thing that helps to understand what's going on. So we should always write them and don't clean them after the test is finished. Perhaps we should clean the log right before the test is run.

**Comment by locker** [comment]
I don't need the log levels and I don't see how they would help me. What I'd like to have to debug test is a *single* log file that would contain messages from *all* test servers and the main test process. It'd be nice if `t.assert` helpers logged into this file as well.

To illustrate what I mean, suppose we have the following test case:

```Lua
g.test_foo = function(cg)
    t.log('message 1')
    cg.server1:exec(function()
        t.log('message 2')
        t.assert_equals(box.info.status, 'running')
    end)
    t.log('message 3')
    cg.server2:exec(function()
        t.log('message 4')
        t.assert_equals(box.info.status, 'running')
    end)
end
```

Then I imagine the log would contain something like this upon running the test case:

```
2023-09-06 19:04:34.742 luatest: begin g.test_foo
2023-09-06 19:04:34.742 luatest: message 1
2023-09-06 19:04:34.743 server1: message 2
2023-09-06 19:04:34.743 server1: assert_equals(box.info.status, 'running')
2023-09-06 19:04:34.744 luatest: message 3
2023-09-06 19:04:34.744 server2: message 4
2023-09-06 19:04:34.745 server2: assert_equals(box.info.status, 'running')
2023-09-06 19:04:34.746 luatest: done g.test_foo
```

**Note** this log file has nothing to do with Tarantool log.

**Comment by alyapunov** [comment]
A couple of thoughts in addition.
1. Actually `log_level = 7` is used very seldom just because it generates tons of useless information about, for example, addressed of created tuples etc.
2. It seems that in case of problems we could set log level right in the test (`box.cfg{log_level=6}`).
3. The most interesting part is usually happens inside of `serverX:exec` call.

This issue is about improving of convenience of writing new tests. We can make mistakes in test and want to find out them, and tarantool itself can do unexpected thing and we want to figure out when and what.
I think that `t.log` would be useful and deserves its own issue.
But I think that the original issue about saving logs in case of failure **including cases of crash or unexpected exit** is still actual.

**Comment by locker** [comment]
Maybe write logs from all instances including the test process to a single file using the Tarantool syslog logger and always save this file? It'd be easier to analyze if one could see the linear history of events from all servers and the test. And if log from a single instance was required, one could easily filter it out by prefix.

**Comment by ochaplashkin** [comment]
We see three related tasks:

1. developer do not see XXXX 1 and XXXX 2 logs from the test (see issue description);
2. the concept of a single logfile (from @locker) + `t.log()` + luatest should log high-level actions (start/end group, before_all/after_all, assert(...), etc);
3. `--debug` (or any other name) parameter of luatest: log low-level actions (create server, wait for condition, etc).

@alyapunov, @locker I suggest solving the first problem and creating separate tasks for the rest.

**Comment by ylobankov** [comment]
Finally, it should be fixed by https://github.com/tarantool/luatest/pull/345.
