### ISSUE TITLE
`assert_error_msg_content_equals()` regexp is too greedy

### ISSUE THREAD

**Issue by Gumix** [tarantool/luatest#316]
https://github.com/tarantool/luatest/blob/4aecd8e7dacd4ec7709659e64643911fe9e37a87/luatest/assertions.lua#L474-L478

It doesn't match `error_msg`, which contains the following pattern:

```lua
local error_msg = "foo:1: bar"
t.assert_error_msg_content_equals(error_msg, error, error_msg)
```

```
[001] not ok 3  gh-0000.engine:"memtx".test_aaaa
[001] #   ...engine-luatest/gh_0000_test.lua:231: Error message expected: "foo:1: bar"
[001] #   Error message received: "foo:1: bar"
```

**Comment by Totktonada** [comment]
AFAIU, `assert_error_msg_equals()` should be used in the case instead of `assert_error_msg_content_equals()`.
