### ISSUE TITLE
Test directory is polluted with `luatest.log` file

### ISSUE THREAD

**Issue by locker** [tarantool/luatest#373]
Change directory to `tarantool/test` and run any test written in luatest, for example `./test-run.py box-luatest/watcher_test.lua`, then check `git status`:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../luatest.log
        luatest.log
```

The `luatest.log` file is also created and never deleted if a test is executed without test-run, for example `luatest box-luatest/watcher_test.lua`:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        luatest.log
```

luatest must not create files in the test directory unless explicitly asked to.

Reproduced with https://github.com/tarantool/tarantool/commit/735b0dce76ff83a748e922b292580ebf48f2e946.

**Comment by d-enk** [comment]
even `luatest -h` creates a `luatest.log` file
this is very strange behavior
