### ISSUE TITLE
Make user friendly README

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/luatest#42]
I don't understand how I should start the `luatest` and what kind of asserts I have. I don't want to make a trip to the `luaunit` pages for this kind informations. It prevents me to make a fast start for testing my application.

**Comment by artur-barsegyan** [comment]
Highlight the text about naming convention which needed for test starting. It prevents new users from the first 15-30 minutes of pain.

**Comment by printercu** [comment]
I hope this one is fixed in master. Feel free to reopen.
