### ISSUE TITLE
Make capture work with large output

### ISSUE THREAD

**Issue by printercu** [tarantool/luatest#6]
Capture uses OS's pipes which have limited capacity. When pipe is full it pauses blocking `write` call and makes non-blocking call failed. To avoid this Capture have to repeatedly read from the pipe and buffer the outputs. This can be done with fiber. While it should work for capturing output from external processes, it does not work with sync io methods which don't `yield` within test runner (ex., `io.stdout:write()`).

**Comment by rosik** [comment]
It's not a problem. We don't use blocking io calls in tarantool.

**Comment by printercu** [comment]
Do you have idea why fix in https://github.com/tarantool/luatest/commit/3508275fd58774e9779ab081a0b122d48ce27458 does not work for this test? https://github.com/tarantool/luatest/blob/3508275fd58774e9779ab081a0b122d48ce27458/test/capture_test.lua#L21-L29
