### ISSUE TITLE
Add more number comparing assertions

### ISSUE THREAD

**Issue by akudiyar** [tarantool/luatest#76]
Currently, numbers can be compared using `assert_equals` or `assert_almost_equals`, but in case if two numbers must be compared for greatness/smallness, the only option is to use simple assert with an expression inside (like `assert(5 > 3)`). Simple asserts say nothing about the compared values in case of failure, only that the result value is not true/false.

I suggest adding more convenient methods like:
 - `assert_greater(number1, number2)`,
 - `assert_greater_or_equals(number1, number2)`,
 - `assert_lesser(number1, number2)`,
 - `assert_lesser_or_equals(number1, number2)`,

which will produce an output like
`expected: <number1 value> is greater or equal <number2 value>, actual: false`

**Comment by knazarov** [comment]
greater_or_equals -> greater_or_equal
lesser_or_equals -> less_or_equal

**Comment by knazarov** [comment]
or better yet, _gt, _lt, _le, etc...

**Comment by Steap2448** [comment]
Closed via #126
