### ISSUE TITLE
`assert_msg_contains` does not use extra message in third argument

### ISSUE THREAD

**Issue by RunsFor** [tarantool/luatest#95]
Example: 

```lua
tarantool> t.assert_str_contains('foo', 'bar', '42')
---
- error:
    status: fail
    class: LuaUnitError
    message: Could not find pattern "bar" in string "foo"
...
```

Working example for `assert_equals` matcher:

```lua
tarantool> t.assert_equals('foo', 'bar', '42')
---
- error:
    status: fail
    class: LuaUnitError
    message: '42

      expected: "bar"

      actual: "foo"'
...
```

**Comment by printercu** [comment]
It has slightly different signature `assert_str_contains (value, expected[, is_pattern[, message]])`. Same for other string assertions. Unfortunately these are legacy methods from luaunit, I don't know if it's good idea to change the api now.
